
platform :ios, '13.0'

target 'Flash Chat iOS13' do
  use_frameworks!

#   Pods for Flash Chat iOS13
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
