// EXCEPTION
// Interrption in the inrended execution of the code

// ERROR
// Unintended interruption in the execution of the code,
// typically show up as exceptions.
// Syntax errors are a type of exceptions that occurs when incorrect syntax is used.

// THROWING AN EXCEPTION
// Sending a message that something has gone wrong in the intended execution of code.
// This can be thrown by JavaScript or by the developer with the `throw` keyword

// =================================================================
// (Comment and Uncomment code one-by-one)
// =================================================================

// throw 'myException'
// throw true

// =================================================================
// (LEAVE CODE HERE AS IT IS)
// function criticalCode() {
//   throw "The error message generated by the function will go here.";
// }
// =================================================================

// try {
//   criticalCode();
// } catch (ex) {
//   console.log("Got an Error");
//   console.log("ERROR :>> ", ex);
// }

// =================================================================

// try {
//   throw "An exception thrown everytime code execution reaches here.";
// } catch (ex) {
//   console.log("Got an Error");
//   console.log("ERROR :>> ", ex);
// }

// =================================================================

// try {
//   throw "An exception thrown everytime code execution reaches here.";
// } catch (ex) {
//   console.log("Got an Error");
//   console.log("ERROR :>> ", ex);
// } finally {
//   console.log("Code that will always run.");
// }

// =================================================================
